### ISSUE TITLE
Testes quebrando

### ISSUE THREAD

**Issue by julioc98** [novatrixtech/gobrtempo#2]
Acho que seria interessante colocar um CI para rodar os testes em todas as modificações alem de arrumar os testes já existentes

**Comment by julioc98** [comment]
Mandei um PR arrumando uma parte... mas ainda acho interessante usar o CI

https://github.com/novatrixtech/gobrtempo/pull/3

**Comment by jeffprestes** [comment]
Concordo.
Fique à vontade para implementar e se precisar de um email para criar a
conta para isso me avise em PVT.

**Comment by julioc98** [comment]
No PR https://github.com/novatrixtech/gobrtempo/pull/4 consegui colocar o CI para rodar
